#!/bin/bash
clear

### - start export >----------------->>
## ----------------->> Script By Dotycat
## ----------------->> Visit our website wwww.dotycat.com

export RED='\033[0;31m'
export GRAY="\e[1;30m"
export BLUE="\033[36m"
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BG='\033[44m'
export NC='\033[0m'

export ERROR="[${RED} ERROR ${NC}]";
export INFO="[${YELLOW} INFO ${NC}]";
export OKEY="[${GREEN} OKEY ${NC}]";
export PENDING="[${YELLOW} PENDING ${NC}]";
export SEND="[${YELLOW} SEND ${NC}]";
export RECEIVE="[${YELLOW} RECEIVE ${NC}]";

export IP=$(curl -sS ifconfig.me)

### Visit our website << -------------<
### www.dotycat.com   <<--------------<
############# - end   <<--------------<
clear
echo -e " ${BLUE}┌────────────────────────────────────────────────────┐${NC}"
echo -e " ${BLUE}│${NC}${RED}        ___   ___ _______   _____   _ _____         ${NC}${BLUE}│${NC}"
echo -e " ${BLUE}│${NC}${RED}       |   \ / _ \_   _\ \ / / __| /_\_   _/        ${NC}${BLUE}│${NC}"
echo -e " ${BLUE}│${NC}${RED}       | |) | (_) || |  \ V / (__ / _ \| |          ${NC}${BLUE}│${NC}"
echo -e " ${BLUE}│${NC}${RED}       |___/ \___/ |_|   |_| \___/_/ \_\_|          ${NC}${BLUE}│${NC}"
echo -e " ${BLUE}│${NC}                                                    ${BLUE}│${NC}"
echo -e " ${BLUE}│${NC}                  WWW.DOTYCAT.COM                   ${BLUE}│${NC}"
echo -e " ${BLUE}│${NC}       TELEGRAM CH ${RED}@dotycat${NC} ADMIN ${RED}@anzclan${NC}          ${BLUE}│${NC}"
echo -e " ${BLUE}└────────────────────────────────────────────────────┘${NC}"
echo -e " ${BLUE}•────────────────────────────────────────────────────•${NC}"
sudo passwd root
sudo apt install curl -y
sudo apt update && sudo apt upgrade -y
sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
service sshd restart
echo -e "$INFO Successfully , Try Login Using 'root' Users"
echo -e "$BLUE•────────────────────────────────────────────────────•$NC"
echo -e ""
read -n 1 -s -r -p "  Press any key to reboot"
reboot
